project:
  type: book
  execute-dir: project

execute:
  eval: true
  echo: true
  output: false
  freeze: false  # auto: during global project renders, re-render only when source changes

book:
  title: "Get IRS data for possible use as PUF targets"
  subtitle: "Create csv file"
  author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - prepare_potential_targets.qmd
    - examine_potential_targets.qmd
    - summarize_puf_for_irs_comparison.qmd
    # - map_puf_variable_names_to_irs_spreadsheet_locations.qmd

format:
  html:
    theme: cosmo
    code-fold: true

editor_options:
  chunk_output_type: console
